### PR TITLE
Improved fetching CoreData entities by batch of records, not by one

### PR DESCRIPTION
**Pull request by vandrusik**
Function `update(with syncSpace: SyncSpace)` is processing each asset/entry one by one, and this cause to many CoreData fetches in case of many changes in Contentful since previous app launch.
Suggested improvements are fetching with IN predicate, which leads to decreasing count of fetches and speeding up the update process.

### CODE REVIEW

**Comment by mariuskatcontentful** [comment]
@vandrusik thanks for proposing the improvement on the SDK but some tests were reported as failing. Unless those are passing i am afraid i can not merge it.

**Comment by vandrusik** [comment]
> @vandrusik thanks for proposing the improvement on the SDK but some tests were reported as failing. Unless those are passing i am afraid i can not merge it.

@mariuskatcontentful 
Hey, I have looked at logs, this is a problem with one test, with name testCanContinueSyncWithExistingToken.
It has error on master branch as well, so it seems not my changes issue.

In the test, you are comparing that entries.count with 0, but actual value is 1.
Looks like somebody has updated some Contentful entry in space dqpnpm0n4e75, and now the test is failing.
You should change the test to compare with 1 (line 111 in ContentfulPersistenceTests.swift), or to use fresh syncTokenId (line 106).

**Comment by mariuskatcontentful** [comment]
Yes, sorry it was my bad i fixed the content in the cloud and now it should be fine. Are you able to add any tests to support your proposed changes for the future?

**Comment by vandrusik** [comment]
> Yes, sorry it was my bad i fixed the content in the cloud and now it should be fine. Are you able to add any tests to support your proposed changes for the future?

Hey, just added a test for new functionality, please take a look

**Pull request closed without merging**
