### PR TITLE
Fix/stale relationship cache entries

### LINKED ISSUE #122: Sync not removing invalid relationships?
This is the problem I'm having, and I *think* it's on the Contentful sync side…

The problem is this:

1. Content synced where model A has relationship to model B
2. Later, content is updated, removing the relationship between A & B. Both A & B content still exist though, just the relationship is removed
3. Next sync, the relationship still exists in the synced data. I can't see anything in the code that would remove this relationship?

### PR DESCRIPTION
**Pull request by timusus**
Resolves #122, #125 

This PR resolves an issue where previously removed relationships may be inadvertently restored after a full re-sync.

Credit to @protosphere for the fix!

## Issue

Say an object has a field containing a one-to-many relationship, eg.

_Figure 1_

```
 Parent.exampleField
    ______|______
   |      |      |
Child1 Child2 Child3
```

at a later point, the relationship is updated in the Contentful dashboard to contain a different set of children:

_Figure 2_

```
 Parent.exampleField
    ______|______
   |      |      |
Child1 Child2 Child4
```

This relationship is correctly updated during an incremental sync so long as only `Parent` has changed. In the case that `Child3` is re-synced (eg. by performing a full sync), the relationship will erroneously be updated so that `Child3`'s relationship to `Parent` is restored (even though this relationship is not present in the Contentful dashboard):

_Figure 3_
```
    Parent.exampleField
   ___________|_________
   |      |      |      |
Child1 Child2 Child4 Child3
```

## Cause

Looking at the implementation of `RelationshipData`, we can see that relationships are stored keyed by the ID. Looking at the definitions for these IDs:

`ToOneRelationship`:

```
self.id = [parentType, parentId, fieldName, childId.id, childId.localeCode ?? "-"].joined(separator: ",")
```

`ToManyRelationship`:

```
self.id = ([parentType, parentId, fieldName, childIds.first?.localeCode ?? "-"] + childIds.map { $0.id }.sorted()).joined(separator: ",")
```

we can see that for both kinds of relationships, their ID is dependent on the IDs of the child entries. This means that a separate entry is stored in the cache for each combination of parent + field name + children. _i.e._ we have an entry in the cache for the relationship depicted in _Figure 1_, and another for the relationship depicted in _Figure 2_).

This does not cause issues during an incremental sync where only `Parent` is updated, as the relationship cache is not used here. However, if `Child3` is updated (as in a full sync), `SynchronizationManager` will ask the cache for any relationships it has stored for `Child3`. Because both the relationships depicted in _Figure 1_ and _Figure 2_ exist in the cache, a relationship between `Child3` and `Parent` is found (*even though this does not exist in the Contentful dashboard*) and restored, creating the (incorrect) relationships as shown in `Figure 3`.

## Solution

To fix this issue, we need to ensure that the cache only stores a single entry for a given parent object and field name; this means that any updates to the field's referenced children will overwrite the existing (now stale) entry in the cache, instead of allowing the stale entry to persist.

To achieve this, the ID of a relationship is now defined as

```
self.id = [parentType, parentId, fieldName, localeCode].joined(separator: ",")
```

so that it is no longer dependent on its children. Without any changes to the cache, this will not work, as it specifically prevents overwriting entries:

```
guard toManyRelationShips[relationShipId] == nil else { return }
```

```
guard !toOneRelationShips.contains(nested.id) else { return }
```

Our first approach to fixing this remove this check, and modify `append` to clean up child IDs that are no longer part of the relationship. However, it was realised that this was not possible with the current data structure, as `childIdsByParent` does not allow access to child IDs associated with an individual field on the parent, and thus we are unable to determine which child IDs have been removed for a given field.

Instead, we opted to change the data structure of `RelationshipData` to a structure which we think better reflects the data storage requirements. Relationships are now keyed by their parent, field name, and locale (meaning that there is now exactly 1 relationship per parent/field/locale combination), with a reverse-lookup cache to keep the implementation performant. With this structure we are able to determine the change in child IDs, and thus determine which were removed, which allows us to remove them the reverse-lookup cache.

`ToOneRelationship`, `ToManyRelationship`, and `Relationship` have been refactored into a single `Relationship` (with `one` and `many` storage options) in order to ease implementation and reduce code duplication. This has resulted in some minor changes in how `SynchronizationManager` interacts with the cache.

Tests for the behaviour described in the issue have also been added; these were verified to fail on the existing implementation.

## Items Of Note

As the data format of the cache has changed, this effectively causes it to be cleared. This may result in loss of relationships that the relationship cache was designed to preserve. However, we don't believe migrating the existing data is possible, as it will contain stale entries, with no way to determine which entries are the correct ones.

### CODE REVIEW

**Comment by timusus** [comment]
@Contentful please don't let this get stale

**Comment by mariuskatcontentful** [comment]
@timusus could you bring your branch up to speed with the changes in main and i can merge it?

**Comment by timusus** [comment]
Unfortunately it has been a very long time since I worked on this, and I'm not familiar with recent Contentful changes. I don't have any plans to make additional commits.

**Comment by mariuskatcontentful** [comment]
@timusus merged as part of this https://github.com/contentful/contentful-persistence.swift/pull/146 closing this PR

**Pull request closed without merging**
