### PR TITLE
Reuse dateformatters

### PR DESCRIPTION
**Pull request by donnywals**
A bad rebase made PR #157 impossible to reopen from the web UI. Remade the PR here

cc. @mariuskatcontentful

### CODE REVIEW

**Comment by donnywals** [comment]
@mariuskatcontentful I'm not able to run the tests / setup the development environment due to the following error:
```
Ld /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OHHTTPStubs.framework/OHHTTPStubs normal (in target 'OHHTTPStubs iOS Framework' from project 'OHHTTPStubs')
    cd /Users/donnywals/Projects/Move\ Agency/contentful-persistence.swift/Carthage/Checkouts/OHHTTPStubs
    /Applications/Xcode-15.4.0-Release.Candidate.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-ios8.0 -dynamiclib -isysroot /Applications/Xcode-15.4.0-Release.Candidate.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk -Os -L/Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/EagerLinkingTBDs/Release-iphoneos -L/Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/BuildProductsPath/Release-iphoneos -F/Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/EagerLinkingTBDs/Release-iphoneos -F/Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/BuildProductsPath/Release-iphoneos -filelist /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/OHHTTPStubs.build/Release-iphoneos/OHHTTPStubs\ iOS\ Framework.build/Objects-normal/arm64/OHHTTPStubs.LinkFileList -install_name @rpath/OHHTTPStubs.framework/OHHTTPStubs -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/OHHTTPStubs.build/Release-iphoneos/OHHTTPStubs\ iOS\ Framework.build/Objects-normal/arm64/OHHTTPStubs_lto.o -fobjc-arc -fobjc-link-runtime -fapplication-extension -L/Applications/Xcode-15.4.0-Release.Candidate.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/OHHTTPStubs.build/Release-iphoneos/OHHTTPStubs\ iOS\ Framework.build/Objects-normal/arm64/OHHTTPStubs.swiftmodule -compatibility_version 1 -current_version 8.0.0 -Xlinker -dependency_info -Xlinker /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/OHHTTPStubs.build/Release-iphoneos/OHHTTPStubs\ iOS\ Framework.build/Objects-normal/arm64/OHHTTPStubs_dependency_info.dat -o /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/OHHTTPStubs/9.1.0/Build/Intermediates.noindex/ArchiveIntermediates/OHHTTPStubs\ iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OHHTTPStubs.framework/OHHTTPStubs
clang: error: SDK does not contain 'libarclite' at the path '/Applications/Xcode-15.4.0-Release.Candidate.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a'; try increasing the minimum deployment target

/Users/donnywals/Projects/Move Agency/contentful-persistence.swift/Carthage/Checkouts/OHHTTPStubs/OHHTTPStubs.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'OHHTTPStubs iOS Framework' from project 'OHHTTPStubs')
** ARCHIVE FAILED **
```

It seems like either OHTTPStubs is very outdated or my Xcode version is newer than what's expected. Do you have any ideas on resolving this?

Also, I'm not able to read the test output on CircleCI (which I was able to do for contentful.swift) which makes it a bit harder to figure out what's not working as expected right now

**Comment by donnywals** [comment]
@mariuskatcontentful I would love to but I'm not able to read the CircleCI output and I'm failing to run the carthage commands that would be needed to grab dependencies before running tests.

Here's the error I'm getting locally:
```
❯ carthage bootstrap --platform all
*** Checking out contentful.swift at "5.5.12"
*** Checking out OHHTTPStubs at "9.1.0"
*** xcodebuild output can be found in /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/carthage-xcodebuild.q9eOOB.log
*** Downloading contentful.swift binary at "5.5.12"
*** Building scheme "Contentful_tvOS" in Contentful.xcworkspace
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -workspace /Users/donnywals/Projects/Move\ Agency/contentful-persistence.swift/Carthage/Checkouts/contentful.swift/Contentful.xcworkspace -scheme Contentful_tvOS -configuration Release -derivedDataPath /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/contentful.swift/5.5.12 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/contentful.swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/donnywals/Projects/Move Agency/contentful-persistence.swift/Carthage/Checkouts/contentful.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/carthage-xcodebuild.q9eOOB.log
```

The following is the contents for the build log:

```
/usr/bin/xcrun xcodebuild -workspace /Users/donnywals/Projects/Move\ Agency/contentful-persistence.swift/Carthage/Checkouts/contentful.swift/Contentful.xcworkspace -scheme Contentful_tvOS -configuration Release -derivedDataPath /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/contentful.swift/5.5.12 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/contentful.swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/donnywals/Projects/Move Agency/contentful-persistence.swift/Carthage/Checkouts/contentful.swift)Command line invocation:
    /Applications/Xcode-15.4.0-Release.Candidate.app/Contents/Developer/usr/bin/xcodebuild -workspace "/Users/donnywals/Projects/Move Agency/contentful-persistence.swift/Carthage/Checkouts/contentful.swift/Contentful.xcworkspace" -scheme Contentful_tvOS -configuration Release -derivedDataPath /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/contentful.swift/5.5.12 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/contentful.swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO

User defaults from command line:
    IDEArchivePathOverride = /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/contentful.swift
    IDEDerivedDataPathOverride = /Users/donnywals/Library/Caches/org.carthage.CarthageKit/DerivedData/15.4_15F31c/contentful.swift/5.5.12
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos17.5
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO
    VALIDATE_WORKSPACE = NO

2024-08-23 11:43:34.251 xcodebuild[4479:32346857] Writing error result bundle to /var/folders/hb/8_ry2v5d06n3k16wksjvr2m80000gn/T/ResultBundle_2024-23-08_11-43-0034.xcresult
xcodebuild: error: Found no destinations for the scheme 'Contentful_tvOS' and action archive.
```

I'm trying to follow instruction from the `README.md` and have run `make setup_env` successfully before bootstrapping

**Comment by donnywals** [comment]
@mariuskatcontentful I'm still stuck on the above

**Comment by donnywals** [comment]
@mariuskatcontentful I'm eagerly awaiting some assistance here in order to fix the tests and get this merged...

**Comment by mariuskatcontentful** [comment]
@donnywals for your convenience recreated the pull request with everything fixed and will merge immediately after tests pass

https://github.com/contentful/contentful-persistence.swift/pull/160

Will do a persistence release later today to production

**Comment by donnywals** [comment]
Awesome @mariuskatcontentful, thanks. Looks like the issue was that the files somehow didn't end up in the Xcode project file? Anyway, thanks for the fix 👍

**Pull request closed without merging**
