### PR TITLE
Added carthage file with dependancy to main lib. Fix swift global method namespace error.

### PR DESCRIPTION
**Pull request by abakhtin**
Hi, 

I had some test with framework and add carthage support. Actually I found that it absolutely not working for entities sync. Can you add it in description? As it is mentioned in docs and I supposed to use it.

### CODE REVIEW

**Comment by loudmouth** [comment]
Hi @abakhtin thanks so much for your contribution. I checked out your branch and found that carthage installation did not work. As there is already a github issue and another pull request open for carthage support (see #15 and #14) I will take this task over from here.

The best way forward is to manage internal dependencies with Carthage instead of Cocoapods so that the added buildphases that Cocoapods injects are removed.

As an added note, there is a specific reason for there being 4 shared xcode schemes in the project—each is to build for the various platforms that Apple so that this library can be integrated for projects supporting either iOS, macOS, tvOS, or watchOS. I'll post a new PR and close this one later today. Thanks again.

**Comment by abakhtin** [comment]
Hi @loudmouth 
My concern was to use it only for iOS, that is why i use single shared shema. Sorry for it. I don't understand what you mean by "found that carthage installation did not work." becouse it works on my side for iOS only. 
If you need any help please let me know. 
As I see the only way to support both pods and carthage is to use separate targets for them. How can you tell the carthage to use concrete one?

**Comment by loudmouth** [comment]
Essentially, what I've learned is that it's easy to support cocoapods installation while using carthage internally, but not the other way around. The `ContentfulPersistenceSwift.podspec` will still be valid even if carthageis how the project builds internally. Thus, my plan is to deintegrate cocoapods from this project and migrate to carthage (the project setup will mirror the main sdk [contentful.swift](https://github.com/contentful/contentful.swift))

Just for reference, I've pasted the output of is the output of the attempt a `carthage bootstrap` from this branch below.

Stay tuned for fixed carthage support. Should be coming later today.

```
$ carthage bootstrap --platform all
*** No Cartfile.resolved found, updating dependencies
*** Cloning contentful-persistence.swift
*** Fetching contentful.swift
*** Fetching Interstellar
*** Fetching ObjectMapper
*** Checking out Interstellar at "2.0.0"
*** Checking out ObjectMapper at "2.2.6"
*** Checking out contentful.swift at "0.4.0"
*** Checking out contentful-persistence.swift at "d1692e8c654af57c61ca5d49dad7473d11aeeb9e"
*** xcodebuild output can be found in /var/folders/26/1d_y04ns6n5chkr4jw54crw00000gn/T/carthage-xcodebuild.zFeQbM.log
*** Building scheme "Interstellar_iOS" in Interstellar.xcodeproj
*** Building scheme "Interstellar_watchOS" in Interstellar.xcodeproj
*** Building scheme "Interstellar_OSX" in Interstellar.xcodeproj
*** Building scheme "Interstellar_tvOS" in Interstellar.xcodeproj
*** Building scheme "ObjectMapper-Mac" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-tvOS" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-watchOS" in ObjectMapper.xcworkspace
*** Building scheme "Contentful_macOS" in Contentful.xcodeproj
*** Building scheme "Contentful_tvOS" in Contentful.xcodeproj
*** Building scheme "Contentful_iOS" in Contentful.xcodeproj
*** Building scheme "Contentful_watchOS" in Contentful.xcodeproj
*** Building scheme "ContentfulPersistence" in ContentfulPersistence.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/loudmouth/pro/Contentful/TestInstalls/Carthage/Checkouts/contentful-persistence.swift/ContentfulPersistence.xcworkspace -scheme ContentfulPersistence -configuration Release -derivedDataPath /Users/loudmouth/Library/Caches/org.carthage.CarthageKit/DerivedData/contentful-persistence.swift/d1692e8c654af57c61ca5d49dad7473d11aeeb9e -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

**Comment by loudmouth** [comment]
Fixed in #17

**Pull request closed without merging**
